server:
  port: 8880
spring:
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        legacy_limit_handler: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/cn_database
    username: cn_user
    password: 1
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
