POST http://localhost:8880/api/v1/contact
x-username: mwarrick0
Content-Type: application/json

{
  "firstName": "Diego",
  "lastName": "Balderrama",
  "username": "dbalderrama",
  "email": "dbalderrama@gmail.com",
  "dateOfBirth": "2021-02-23",
  "seed": "xx"
}

###

GET http://localhost:8880/api/v1/contact/1
x-username: mwarrick0

###

GET http://localhost:8880/api/v1/contact/list?code=dateOfBirth&value=2021-02-03;2021-06-08
x-username: mwarrick0

###

PUT http://localhost:8880/api/v1/contact/31
x-username: mwarrick0
Content-Type: application/json

{
  "firstName": "Diegos",
  "lastName": "Balderramas",
  "username": "dbalderramas",
  "email": "dbalderrama@gmail.coms",
  "dateOfBirth": "2021-02-23",
  "seed": "xx"
}

###

POST http://localhost:8880/api/v1/contact/relation
x-username: mwarrick0
Content-Type: application/json

{
  "contactUsername": "nwyllcockt",
  "requestUsername": "mwarrick0",
  "relation": "Brother",
  "acquaintanceDate": "2021-02-23"
}

###